openapi: 3.1.0
info:
  title: Weaver API
  version: 1.0.0
  description: Minimal contract for chat endpoints
servers:
  - url: http://localhost:4101
paths:
  /v1/chat:
    post:
      summary: Create chat completion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Chat response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
  /v1/chat/stream:
    post:
      summary: Stream chat completion via SSE
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: SSE stream of deltas
          content:
            text/event-stream:
              schema:
                type: string
components:
  schemas:
    Message:
      type: object
      required: [role, content]
      properties:
        role:
          type: string
          enum: [system, user, assistant]
        content:
          type: string
    ChatRequest:
      type: object
      required: [messages]
      properties:
        model:
          type: string
          description: Provider-specific model id
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
        temperature:
          type: number
          minimum: 0
          maximum: 2
    ChatResponse:
      type: object
      required: [content]
      properties:
        content:
          type: string
        modelUsed:
          type: string
        engine:
          type: string
