version: '3.8'
services:
  api:
    build:
      context: ../api
      dockerfile: ../deploy/Dockerfile
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ../frontend
      dockerfile: ../deploy/Dockerfile
    ports:
      - "5173:5173"
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weavers_studio
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
volumes:
  db_data:
