name: CI
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  id-token: write
  contents: read

env:
  GCP_PROJECT_ID: weaver-studios
  GCP_PROJECT_NUMBER: 413404577713

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Google Auth (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ env.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/weaver-ci-pool/providers/github
          service_account: weaverstudiovault@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com

      - name: Configure gcloud
        run: gcloud config set project "$GCP_PROJECT_ID"

      - name: Verify identity
        run: |
          gcloud auth list
          gcloud --quiet services enable iamcredentials.googleapis.com || true
          echo "Service Account: weaverstudiovault@${GCP_PROJECT_ID}.iam.gserviceaccount.com"
