name: Secret Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          version: latest
          config-path: .gitleaks.toml
          verbose: true
          redact: true

      - name: Run gitleaks (explicit)
        run: gitleaks detect --config=.gitleaks.toml --no-banner --redact --exit-code 2 || exit_code=$?; echo "GITLEAKS_EXIT_CODE=$exit_code" >> $GITHUB_ENV; exit $exit_code

  fallback-regex:
    if: always() && needs.gitleaks-scan.result == 'failure'
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fallback regex scan
        run: |
          echo 'Running lightweight regex scan (gitleaks failed or findings)'
          grep -RIE --line-number --color=never -e 'API_KEY' -e 'BEGIN RSA PRIVATE KEY' -e 'AIza[0-9A-Za-z_-]{35}' . || true
